Q1.Write a Python program to generate a random alphabetical string, random value between two integers (inclusive) and a random multiple of 7 between 0 and 70. 

In [1]:
import random
import string

# Generate a random alphabetical string
alphabet = string.ascii_letters
random_string = ''.join(random.choice(alphabet) for i in range(10))

# Generate a random integer between 1 and 10 (inclusive)
random_int = random.randint(1, 10)

# Generate a random multiple of 7 between 0 and 70
random_multiple = random.randrange(0, 71, 7)

# Print the results
print("Random alphabetical string:", random_string)
print("Random integer between 1 and 10:", random_int)
print("Random multiple of 7 between 0 and 70:", random_multiple)


Random alphabetical string: LvRlXPXdxg
Random integer between 1 and 10: 7
Random multiple of 7 between 0 and 70: 56


In [2]:
import random
import string

def generate_random_values():
    # Generate a random alphabetical string
    alphabet = string.ascii_letters
    random_string = ''.join(random.choice(alphabet) for i in range(10))

    # Generate a random integer between two given values (inclusive)
    min_val = int(input("Enter minimum value: "))
    max_val = int(input("Enter maximum value: "))
    random_int = random.randint(min_val, max_val)

    # Generate a random multiple of 7 between 0 and 70
    random_multiple = random.randrange(0, 71, 7)

    # Return a tuple with the generated values
    return random_string, random_int, random_multiple


In [3]:
random_string, random_int, random_multiple = generate_random_values()
print("Random alphabetical string:", random_string)
print("Random integer:", random_int)
print("Random multiple of 7:", random_multiple)


Enter minimum value: 1
Enter maximum value: 10
Random alphabetical string: SZcWPMXnjs
Random integer: 10
Random multiple of 7: 7


Q2.Write a python program to print the no. of days to reach your birthday from today.


In [5]:
import datetime

def days_until_birthday(birthdate):
    """
    Calculate the number of days until the next birthday.
    """
    today = datetime.date.today()
    next_birthday = datetime.date(today.year, birthdate.month, birthdate.day)
    if next_birthday < today:
        next_birthday = datetime.date(today.year + 1, birthdate.month, birthdate.day)
    time_to_birthday = next_birthday - today
    return time_to_birthday.days

In [16]:
year = int(input("Enter your birth year (YYYY): "))
month = int(input("Enter your birth month (MM): "))
day = int(input("Enter your birth day (DD): "))
birthdate = datetime.date(year, month, day)
days = days_until_birthday(birthdate)
print("There are", days, "days until your next birthday.")

Enter your birth year (YYYY): 1995
Enter your birth month (MM): 7
Enter your birth day (DD): 13
There are 140 days until your next birthday.


In [44]:
#Write a python program to print the no. of days to reach your birthday from today.
from datetime import datetime
d1=datetime(1995,7,13)
d2=datetime.now()

d1=datetime(d2.year,d1.month,d1.day)

if d1.month<d2.month:
    d1=datetime(d2.year+1,d1.month,d1.day)
print(abs((d1-d2).days))

139


In [17]:
import datetime

def days_until_birthday(birthdate):
    """
    Calculate the number of days until the next birthday.
    """
    today = datetime.date.today()
    next_birthday = datetime.date(today.year, birthdate.month, birthdate.day)
    if next_birthday < today:
        next_birthday = datetime.date(today.year + 1, birthdate.month, birthdate.day)
    time_to_birthday = next_birthday - today
    return time_to_birthday.days

def main():
    """
    Prompt the user to input their birthdate and print the number of days until their next birthday.
    """
    year = int(input("Enter your birth year (YYYY): "))
    month = int(input("Enter your birth month (MM): "))
    day = int(input("Enter your birth day (DD): "))
    birthdate = datetime.date(year, month, day)
    days = days_until_birthday(birthdate)
    print("There are", days, "days until your next birthday.")

if __name__ == "__main__":
    main()


Enter your birth year (YYYY): 1995
Enter your birth month (MM): 7
Enter your birth day (DD): 13
There are 140 days until your next birthday.


In [22]:
from datetime import date
f_date = date(2014, 7, 2)
l_date = date(2014, 7, 11)
delta = l_date - f_date
print(delta.days)

9


Q3. Write a Python program to get a list of locally installed Python modules.


In [24]:
import pkg_resources
installed_packages = pkg_resources.working_set
installed_packages_list = sorted(["%s==%s" % (i.key, i.version)
     for i in installed_packages])
for m in installed_packages_list:
    print(m)

alabaster==0.7.12
anaconda-client==1.11.0
anaconda-navigator==2.3.1
anaconda-project==0.11.1
anyio==3.5.0
appdirs==1.4.4
argon2-cffi-bindings==21.2.0
argon2-cffi==21.3.0
arrow==1.2.2
astroid==2.11.7
astropy==5.1
atomicwrites==1.4.0
attrs==21.4.0
automat==20.2.0
autopep8==1.6.0
babel==2.9.1
backcall==0.2.0
backports.functools-lru-cache==1.6.4
backports.tempfile==1.0
backports.weakref==1.0.post1
bcrypt==3.2.0
beautifulsoup4==4.11.1
binaryornot==0.4.4
bitarray==2.5.1
bkcharts==0.2
black==22.6.0
bleach==4.1.0
bokeh==2.4.3
boto3==1.24.28
botocore==1.27.28
bottleneck==1.3.5
brotlipy==0.7.0
certifi==2022.9.14
cffi==1.15.1
chardet==4.0.0
charset-normalizer==2.0.4
click==8.0.4
cloudpickle==2.0.0
clyent==1.2.2
colorama==0.4.5
colorcet==3.0.0
colorlover==0.3.0
comtypes==1.1.10
conda-build==3.22.0
conda-content-trust==0.1.3
conda-pack==0.6.0
conda-package-handling==1.9.0
conda-repo-cli==1.0.20
conda-token==0.4.0
conda-verify==3.4.2
conda==22.9.0
constantly==15.1.0
cookiecutter==1.7.3
cryptography=

In [12]:
import pkgutil
from setuptools import find_packages

def get_installed_modules():
    installed_modules = []
    for module in pkgutil.iter_modules():
        installed_modules.append(module.name)
    for package in find_packages():
        installed_modules.append(package)
    return installed_modules

installed_modules = get_installed_modules()
print(installed_modules)

Q4.4. Create the following NumPy arrays:

    
a) A 1D array called ‘zeros’ having 10 elements and all the elements are set to zero.

b) A 1D array called ‘vowels’ having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’.

c) A 2D array called ‘ones’ having 2 rows and 5 columns and all the elements are set to 1 and dtype as int.

d) Use nested Python lists to create a 2D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7, -2, -19, 0, 3.4, 99.9, 10.6, 0, 13.

e) A 2D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float.


In [31]:
import numpy as np

# a) A 1D array called ‘zeros’ having 10 elements and all the elements are set to zero.
zeros = np.zeros(10)

# b) A 1D array called ‘vowels’ having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’.
vowels = np.array(['a', 'e', 'i', 'o', 'u'])

# c) A 2D array called ‘ones’ having 2 rows and 5 columns and all the elements are set to 1 and dtype as int.
ones = np.ones((2, 5), dtype=int)

# d) Use nested Python lists to create a 2D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7, -2, -19, 0, 3.4, 99.9, 10.6, 0, 13.
myarray1 = np.array([[2.7, -2, -19], [0, 3.4, 99.9], [10.6, 0, 13]])



In [32]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
vowels

array(['a', 'e', 'i', 'o', 'u'], dtype='<U1')

In [34]:
ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
myarray1

array([[  2.7,  -2. , -19. ],
       [  0. ,   3.4,  99.9],
       [ 10.6,   0. ,  13. ]])

Q5.Using the arrays created in Question 4 above, write NumPy commands for the following:

a) Find the dimensions, shape, size, data type of the items and itemsize of arrays ‘zeros’, ‘vowels’, ‘ones’, myarray1 and myarray2.

b) Reshape the array ‘ones’ to have all the 10 elements in a single row.

c) Display the 2nd and 3rd element of the array ‘vowels’.

d) Display all elements in the 2nd and 3rd row of the array ‘myarray1’.

e) Display the elements in the 1st and 2nd column of the array ‘myarray1’.

f)Display the elements in the 1st column of the 2nd and 3rd row of the array ‘myarray1’.

g) Reverse the array of ‘vowels’.


In [9]:
import numpy as np

# a) create the arrays
zeros = np.zeros(10)
vowels = np.array(['a', 'e', 'i', 'o', 'u'])
ones = np.ones((2, 5), dtype=int)
myarray1 = np.array([[2.7, -2, -19], [0, 3.4, 99.9], [10.6, 0, 13]])
myarray2 = np.arange(start=4, stop=24, step=4, dtype=float)



In [10]:
# b) find dimensions, shape, size, data type, and itemsize of each array
print("zeros dimensions:", zeros.ndim) # 1
print("zeros shape:", zeros.shape) # (10,)
print("zeros size:", zeros.size) # 10
print("zeros data type:", zeros.dtype) # float64
print("zeros itemsize:", zeros.itemsize) # 8

print("vowels dimensions:", vowels.ndim) # 1
print("vowels shape:", vowels.shape) # (5,)
print("vowels size:", vowels.size) # 5
print("vowels data type:", vowels.dtype) # <U1
print("vowels itemsize:", vowels.itemsize) # 4

print("ones dimensions:", ones.ndim) # 2
print("ones shape:", ones.shape) # (2, 5)
print("ones size:", ones.size) # 10
print("ones data type:", ones.dtype) # int64
print("ones itemsize:", ones.itemsize) # 8

print("myarray1 dimensions:", myarray1.ndim) # 2
print("myarray1 shape:", myarray1.shape) # (3, 3)
print("myarray1 size:", myarray1.size) # 9
print("myarray1 data type:", myarray1.dtype) # float64
print("myarray1 itemsize:", myarray1.itemsize) # 8

print("myarray2 dimensions:", myarray2.ndim) # 2
print("myarray2 shape:", myarray2.shape) # (3, 5)
print("myarray2 size:", myarray2.size) # 15
print("myarray2 data type:", myarray2.dtype) # float64
print("myarray2 itemsize:", myarray2.itemsize) # 8


# reshape ones to have all the 10 elements in a single row
ones_reshaped = ones.reshape(1, -1)
print(ones_reshaped)


zeros dimensions: 1
zeros shape: (10,)
zeros size: 10
zeros data type: float64
zeros itemsize: 8
vowels dimensions: 1
vowels shape: (5,)
vowels size: 5
vowels data type: <U1
vowels itemsize: 4
ones dimensions: 2
ones shape: (2, 5)
ones size: 10
ones data type: int32
ones itemsize: 4
myarray1 dimensions: 2
myarray1 shape: (3, 3)
myarray1 size: 9
myarray1 data type: float64
myarray1 itemsize: 8
myarray2 dimensions: 1
myarray2 shape: (5,)
myarray2 size: 5
myarray2 data type: float64
myarray2 itemsize: 8
[[1 1 1 1 1 1 1 1 1 1]]


In [39]:
#c)
# display the 2nd and 3rd element of the array vowels
print(vowels[1:3])



['e' 'i']


In [40]:
# d)
# display all elements in the 2nd and 3rd row of the array myarray1
print(myarray1[1:3])


[[ 0.   3.4 99.9]
 [10.6  0.  13. ]]


In [41]:
# e)
# display the elements in the 1st and 2nd column of the array myarray1
print(myarray1[:, :2])


[[ 2.7 -2. ]
 [ 0.   3.4]
 [10.6  0. ]]


In [42]:
# f)

# display the elements in the 1st column of the 2nd and 3rd row of the array myarray1
print(myarray1[1:3, 0])


[ 0.  10.6]


In [43]:
# g)

# reverse the array of vowels
vowels_reversed = vowels[::-1]
print(vowels_reversed)


['u' 'o' 'i' 'e' 'a']
